//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotsBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotsBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        internal static string CancellableDialog_back {
            get {
                return ResourceManager.GetString("CancellableDialog_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenašel jsem pro Vás žádnou objednávku..
        /// </summary>
        internal static string CrmQueryFailed {
            get {
                return ResourceManager.GetString("CrmQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nashledanou.
        /// </summary>
        internal static string goodbye {
            get {
                return ResourceManager.GetString("goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spojit se s operátorem.
        /// </summary>
        internal static string HelpDialog_connect_operator {
            get {
                return ResourceManager.GetString("HelpDialog_connect_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončit.
        /// </summary>
        internal static string HelpDialog_end {
            get {
                return ResourceManager.GetString("HelpDialog_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypadá to, že si nevíte rady, veberte jednu z možností..
        /// </summary>
        internal static string HelpDialog_Prompt {
            get {
                return ResourceManager.GetString("HelpDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začít znovu.
        /// </summary>
        internal static string HelpDialog_start_over {
            get {
                return ResourceManager.GetString("HelpDialog_start_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na kolik částek si přejete splátku rozdělit? (2 až 24).
        /// </summary>
        internal static string MluviiDialog_instalments_prompt {
            get {
                return ResourceManager.GetString("MluviiDialog_instalments_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohužel se nepodařilo spojit s operátorem. Přejete si začít znovu?.
        /// </summary>
        internal static string MluviiDialog_operator_failed {
            get {
                return ResourceManager.GetString("MluviiDialog_operator_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud si nepřejete nyní zadávat své údaje, můžu Vás místo toho spojit s operátorem..
        /// </summary>
        internal static string MluviiDialog_person_form_cancelled {
            get {
                return ResourceManager.GetString("MluviiDialog_person_form_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabízíme vám úvěr na Vámi vybraný produkt {0} o celkové hodnotě {1} rozdělený na {2} mésičních splátek ve výši {3}  a úrokovou sazbou {4}%.
        /// </summary>
        internal static string MluviiDialog_product_offer {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavřít s živým operátorem.
        /// </summary>
        internal static string MluviiDialog_product_offer_choice_not_tincans {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_choice_not_tincans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsat elektronicky.
        /// </summary>
        internal static string MluviiDialog_product_offer_choice_sign_online {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_choice_sign_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohužel zadané údaje se ani na potřetí neshodují, proto Vás přepojuji na Operátora..
        /// </summary>
        internal static string MluviiDialog_product_offer_sign_failed {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_sign_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Děkujeme, smlouva Vám bude zaslána na Váš email {0}. Produkt {1} si můžete vyzvednout v našem Boxu č. 10..
        /// </summary>
        internal static string MluviiDialog_product_offer_signed {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úroková sazba: {0}.
        /// </summary>
        internal static string MluviiDialog_product_offer_subTitle {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úvěrová smlouva č. {0}.
        /// </summary>
        internal static string MluviiDialog_product_offer_title {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím podepište se. (jméno příjmení).
        /// </summary>
        internal static string MluviiDialog_product_offer_your_signature_here {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_your_signature_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohužel zadané údaje nesouhlasí s údaji v našem systému, prosím podepište se (jméno příjmení)..
        /// </summary>
        internal static string MluviiDialog_product_offer_your_signature_here_retry {
            get {
                return ResourceManager.GetString("MluviiDialog_product_offer_your_signature_here_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtuální asistent.
        /// </summary>
        internal static string MluviiDialog_virtual_assistant {
            get {
                return ResourceManager.GetString("MluviiDialog_virtual_assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobře, momentík podívám se kdo z kolegů je volný..
        /// </summary>
        internal static string MluviiDialog_wait_checking_available_operators {
            get {
                return ResourceManager.GetString("MluviiDialog_wait_checking_available_operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přepojuji Vás na operátora {0}. Prosím strpení..
        /// </summary>
        internal static string OperatorConnect_wait {
            get {
                return ResourceManager.GetString("OperatorConnect_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je nám líto, momentálně nejsou k dispozici žádní operátoři..
        /// </summary>
        internal static string OperatorSelection_none_availible {
            get {
                return ResourceManager.GetString("OperatorSelection_none_availible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerozuměl jsem, můžete to zkusit ještě jednou?.
        /// </summary>
        internal static string RetryText {
            get {
                return ResourceManager.GetString("RetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpet.
        /// </summary>
        internal static string RootDialog_Checkout_Cancel {
            get {
                return ResourceManager.GetString("RootDialog_Checkout_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operátor.
        /// </summary>
        internal static string WelcomeMessage_operator {
            get {
                return ResourceManager.GetString("WelcomeMessage_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},
        ///přejete si uzavřít úvěrovou smlouvu na {1} s pomocí našeho operátora na call centru nebo s pomocí mne - Virtuálního asistenta (ChatBot)?
        ///    .
        /// </summary>
        internal static string WelcomeMessage_prompt {
            get {
                return ResourceManager.GetString("WelcomeMessage_prompt", resourceCulture);
            }
        }
    }
}
